pipeline_id: demo_minio_to_pg
schedule: "0 8 * * *"
retries: 1
tags: ["minio", "generated"]
source:
  type: s3
  conn_id: minio_s3              # Airflow Connection ID for MinIO
  bucket: demo-bucket
  key: raw/users/*.csv           # можно шаблон с *
  format: csv
  options: { }                    # pandas read_csv options (optional)
transforms:
  - type: select
    columns: [id, email, country, created_at]
  - type: cast
    columns:
      id: int
      created_at: timestamp
  - type: filter
    expr: "country in ['AT','DE','CH']"
target:
  type: postgres
  conn_id: pg_dw
  table: dim_users
  mode: append
  batch_size: 10000
quality_checks:
  - type: not_null
    column: id
  - type: unique
    columns: [id]
  - type: row_count_min
    min: 1
